### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by LevitateGamer** [hoplik/Firehose-Finder#35]
`PLATFORM VERSION INFO
	Windows 			: 10.0.22631.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.9176.0 built by: NET481REL1LAST_B
	clr.dll 			: 4.8.9181.0 built by: NET481REL1LAST_C
	dfdll.dll 			: 4.8.9176.0 built by: NET481REL1LAST_B
	dfshim.dll 			: 10.0.22621.30000 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/Levit/Downloads/Publishing/Publishing/FirehoseFinder.application
	Deployment Provider url		: http://fhf.mywebcommunity.org/FirehoseFinder.application
						Server		: Apache
	Application url			: http://fhf.mywebcommunity.org/Application%20Files/FirehoseFinder_23_12_2_0/FirehoseFinder.exe.manifest
						Server		: Apache

IDENTITIES
	Deployment Identity		: FirehoseFinder.application, Version=23.12.2.0, Culture=ru, PublicKeyToken=0000000000000000, processorArchitecture=msil
	Application Identity		: FirehoseFinder.exe, Version=23.12.2.0, Culture=ru, PublicKeyToken=0000000000000000, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Levit\Downloads\Publishing\Publishing\FirehoseFinder.application resulted in exception. Following failure messages were detected:
		+ Downloading http://fhf.mywebcommunity.org/Application Files/FirehoseFinder_23_12_2_0/AdbWinApi.dll.deploy did not succeed.
		+ The remote server returned an error: (503) Server Unavailable.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [1/19/2024 9:55:13 AM] : Activation of C:\Users\Levit\Downloads\Publishing\Publishing\FirehoseFinder.application has started.
	* [1/19/2024 9:55:14 AM] : Processing of deployment manifest has successfully completed.
	* [1/19/2024 9:55:14 AM] : Installation of the application has started.
	* [1/19/2024 9:55:14 AM] : Processing of application manifest has successfully completed.
	* [1/19/2024 9:55:17 AM] : Found compatible runtime version 4.0.30319.
	* [1/19/2024 9:55:17 AM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [1/19/2024 9:56:12 AM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://fhf.mywebcommunity.org/Application Files/FirehoseFinder_23_12_2_0/AdbWinApi.dll.deploy did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote server returned an error: (503) Server Unavailable.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

`

**Comment by hoplik** [comment]
Thanks for the message. It seems that there are some problems with the pay-free server. I'll check it out now, and at the same time I'll upload a new version.

**Comment by hoplik** [comment]
Try PC version while server out.
https://github.com/hoplik/Firehose-Finder/releases/tag/24.1.19.0
